---

date_file_created: 2022-08-02_05:12:43
date_file_modified: 2022-08-02_05:31:29
title: biostat101-kanban
kanban-plugin: basic

---

## 1. Биостатистика обзор

- [ ] Организационные моменты
- [ ] Биостатистика и ее история
- [ ] Место статистики в биологии
- [ ] Генеральная совокупность и выборка
- [ ] Индивидуальная изменчивость
- [ ] Репрезентативность
- [ ] Случайная выборка
- [ ] Независимость наблюдений
- [ ] Повторности
- [ ] Псевдорепликация
- [ ] Погрешности, связанные с наблюдателем
- [ ] Типы данных
- [ ] Категориальные/качественные и числовые/количественные переменные (метрические/мерные, меристические/счетные)
- [ ] Предикторы и отклики
- [ ] Вариационный ряд - просто показываем анонс
- [ ] Распределение - просто показываем анонс
- [ ] Параметры и статистики - просто вводим термины.


## 2. (П) Первые шаги в R

- [ ] История R.
- [ ] Настройка RStudio
- [ ] Установка пакетов
- [ ] R как калькулятор
- [ ] Индексация в векторах (номер)
- [ ] Типы данных
- [ ] Логические операции
- [ ] Фильтрация данных в R


## 3. Описательная статистика (WS3)

- [ ] Разновидности средних: средняя арифметическая, средняя гармоническая, средняя геометрическая, средняя квадратическая, средняя кубическая,
- [ ] Среднее арифметическое, варианса и стандартное отклонение
- [ ] Коэффициент вариации
- [ ] Медиана и межквартильное расстояние
- [ ] Боксплоты
- [ ] Сопоставление свойств средней и медианы, стандартного отклонения и межквартильного расстояния
- [ ] Кумулята и огива
- [ ] Перцентили и квантили
- [ ] Пропорции


## 4. (П) Работа с данными в R

- [ ] Рабочая директория
- [ ] Открытие файлов с данными
- [ ] Датафреймы
- [ ] Индексация в датафреймах (номер, дфр уже с разными типами, но без обсуждения пока)
- [ ] Фильтрация датафреймов
- [ ] Вычисляем описательные статистики в R
- [ ] Пропущенные значения `NA`
- [ ] mean()
- [ ] na.rm = TRUE
- [ ] median()
- [ ] summary()
- [ ] sd()
- [ ] Coef of variation
- [ ] IQR()
- [ ] Гистограммы, боксплоты, точки с усами


## 5. 📊 Визуализация данных - обзор

- [ ] Tidy data
- [ ] Хорошие таблицы
- [ ] Хорошие графики
- [ ] Одна переменная - таблица частот, столбчатый график. Пайчарты и их проблемы
- [ ] Таблица частот и гистограмма. Описание формы гистограммы (асимметрия, эксцесс, выбросы). Классовый интервал.
- [ ] Две категориальные переменные. Таблица сопряженности. Сгруппированные столбики. Мозаичный график.
- [ ] Две численные переменные. Скаттерплот.
- [ ] Численная и категориальная переменные. Точки. Боксплоты (позже подробнее).
- [ ] Множество гистограмм.
- [ ] Тренды во времени и пространстве. Линейный график.
- [ ] Тепловые карты.
- [ ] Карты.
- [ ] Грамматика графиков


## 6. 📊 (П) Графики в R

- [ ] Теория работы в ggplot2
- [ ] Две непрерывных переменных:
- [ ] Скаттерплот
- [ ] Численная и категориальная переменные:
- [ ] Точечный график
- [ ] Столбчатый график
- [ ] Дополнительные переменные - эстетики:
- [ ] Заливка столбиков
- [ ] Цвет точек
- [ ] Форма точек
- [ ] Линейный график
- [ ] Ряды значений
- [ ] Одна переменная и описательная статистика: Гистограмма (stat_count)
- [ ] Дополнительные переменные - фасетки: Ряды цветных гистограмм


## 7. Вероятности и распределения (WS5)

- [ ] Вероятность
- [ ] Свойства вероятности (на примере диаграмм Венна)
- [ ] Независимые события
- [ ] Распределения: дискретные и непрерывные
- [ ] Функция распределения
- [ ] Плотность распределения
- [ ] Действия с вероятностями: - сложение вероятностей, - умножение вероятностей, - сумма вероятностей всех несовместных событий равна 1
- [ ] Зависимые события
- [ ] Условная вероятность
- [ ] Теорема Байеса
- [ ] Колоколообразные кривые
- [ ] Нормальное распределение (WS10)
- [ ] Формула нормального распределения
- [ ] Свойства нормального распределения


## 8. (П) Вероятности и распределения в R

- [ ] Задачи на вероятности
- [ ] Задачи на теорему Байеса
- [ ] Задачи на вероятности с кривой нормального распределения


## 9. Оценка неопределенности (WS4)

- [ ] Выборочное распределение
- [ ] Распределение выборочных средних
- [ ] Центральная предельная теорема (ЦПТ)
- [ ] Стандартная ошибка среднего
- [ ] Стандартизация (Нормированное отклонение)
- [ ] Стандартное нормальное распределение
- [ ] Доверительный интервал для среднего из нормального распределения
- [ ] t-распределение
- [ ] Степени свободы
- [ ] Доверительный интервал для среднего из t-распределения


## 10. (П) Описательная статистика в R

- [ ] Работа с выборками в R (демонстрация ЦПТ?)
- [ ] Вычисление доверительного интервала из нормального распределения
- [ ] Вычисление доверительного интервала из t-распределения


## 11. Тестирование гипотез, сравнение двух групп

- [ ] Нулевая и альтернативная гипотезы.
- [ ] Одновыборочный t-тест
- [ ] Уровень значимости, доверительная вероятность.
- [ ] Ошибки при тестировании гипотез
- [ ] Двухвыборочный t-тест
- [ ] t-тест Уэлча (разные SD)
- [ ] Парный t-тест
- [ ] Сравнение дисперсий (тест Левина)


## 12. (П) Тестирование гипотез, сравнение двух групп в R



## 13. Борьба с отклонениями от условий применимости

- [ ] Графические тесты
- [ ] Трансформации данных
- [ ] Непараметрические методы и их условия применимости
- [ ] Бутстреп и его условия применимости


## 14. (П) Борьба с отклонениями от условий применимости

- [ ] Трансформация данных в R
- [ ] Проверка на нормальность в R
- [ ] Непараметрические методы в R
- [ ] Бутстреп в R


## 15. Пропорции и частоты

- [ ] Биномиальное распределение
- [ ] Биномиальный тест для пропорций
- [ ] Доверительные интервалы для пропорций
- [ ] Пропорциональная модель
- [ ] хи-квадрат тест качества подгонки
- [ ] Условия применимости хи-квадрат теста качества подгонки
- [ ] Тесты для двух категорий


## 16. (П) Пропорции и частоты в R



## 17. Случайность в пространстве или времени

- [ ] Распределение Пуассона
- [ ] Тестирование случайности расположения при помощи распределения Пуассона
- [ ] Закономерности распределения (размещения) особей в пространстве: случайное, регулярное, агрегированное. Индекс структурности. Причины неслучайности в распределении биологических признаков и объектов. Оценка достоверности характера распределения особей (d-статистика).


## 18. (П) Случайность в пространстве или времени в R



## 19. Связь между категориальными переменными

- [ ] Связь категориальных переменных
- [ ] Шансы
- [ ] Относительный риск
- [ ] тест сопряженности хи-квадрат
- [ ] Ожидаемые частоты при условии независимости
- [ ] Хи-квадрат статистика для таблиц 2х2
- [ ] Условия применимости теста хи-квадрат
- [ ] Коррекция на непрерывность
- [ ] Точный тест Фишера


## 20. (П) Связь категориальных переменных в R



## 21. Дисперсионный анализ 1

- [ ] Однофакторный дисперсионный анализ
- [ ] Многофакторный дисперсионный анализ
- [ ] Взаимодействие
- [ ] ~~Пост хок тесты~~
- [ ] Сила влияния факторов
- [ ] Фиксированные и случайные факторы
- [ ] Условия применимости дисперсионного анализа
- [ ] Тест Краскала-Уоллиса


## 22. (П) Дисперсионный анализ в R



## 23. Корреляция и регрессия

- [ ] Матрица корреляций
- [ ] Тестирование значимости коэффициента корреляции
- [ ] Интерпретация величины коэффициента корреляции
- [ ] Ранговые коэффициенты корреляции (Спирмена, Кендала)
- [ ] Корреляционное отношение (?)
- [ ] Автокорреляция
- [ ] Частная корреляция
- [ ] Простая линейная регрессия
- [ ] Множественная линейная регрессия
- [ ] Условия применимости линейной регрессии


## 24. (П) Корреляция и регрессия в R





%% kanban:settings
```
{"kanban-plugin":"basic"}
```
%%