---
title: "Основы биостатистики"
description: ""
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
    theme: lumen
    highlight: haddock
    include:
      after_body: _footer.html
    css: styles.css
    lib_dir: site_libs
    self_contained: no
---
 
## О курсе

Курс "Основы биостатистики" задуман как первый, самый базовый курс статистики для студентов-нематематиков. Слушатели познакомятся с основными терминами и понятиями биостатистики и узнают, как работают наиболее распространенные в биологии процедуры статистического анализа (базовая описательная статистика, тестирование гипотез, основы непараметрических методов, методы анализа долей, частот, счетных данных, дисперсионный, корреляционный и регрессионный анализ).

Практические занятия в этой редакции курса будут проводиться с использованием языка статистического программирования R. 

### Расписание и контакты

- Варфоломеева Марина Александровна - marina.varfolomeeva[]gmail.com

### Задания, дедлайны и оценки

Тренировочные задания и вопросы для самоконтроля на Stepik будут появляться каждую неделю после занятия. Жестких дедлайнов не будет, но лучше всего, чтобы вы успевали решить эти задания до следующего занятия. Это поможет вам лучше усвоить материал и избежать авралов и бессонных ночей.

В конце курса будет итоговый тест.

```{r eval=FALSE, echo=FALSE}
# Максимальный балл без пересдач (дз + финальный тест)
max_grade <- 291
# Ниж. границы оценок в долях от 1, начиная от самой плохой E
# Из приказа в Ун-те
breaks_prop <- c(0.5, 0.61, 0.7, 0.8, 0.9)
# Ниж. границы оценок в баллах
breaks_grade <- round(max_grade * breaks_prop, 1)
# Знаки неравенства для красоты
dividers <- c(paste( " <=", LETTERS[5:2], "< "), "<= A")
# Границы оценок по ECTS
ECTS_string <- paste(breaks_grade, dividers)
cat(ECTS_string)
# 145.5  <= E <  177.5  <= D <  203.7  <= C <  232.8  <= B <  261.9 <= A
# Генерируем формулу для calc
# cat(paste0('=ifs(', paste0('B4 < ', breaks_grade, ', "', c("Незачет", LETTERS[5:2]), collapse = '", '), '", B4 >= ', breaks_grade[5], ', "A")'))
=ifs(B4 < 145.5, "Незачет", B4 < 177.5, "E", B4 < 203.7, "D", B4 < 232.8, "C", B4 < 261.9, "B", B4 >= 261.9, "A")
```
