---
title: "Презентации и данные"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
    theme: lumen
    highlight: haddock
    include:
      after_body: _footer.html
    css: styles.css
    lib_dir: site_libs
    self_contained: no
---

## 1. Биостатистика, обзор

- Презентация [01-overview.html](01-overview.html)

## 2. Знакомство с R

- Код [02-r-intro.R](02-r-intro.R)

## 3. Описательная статистика

- Презентация [03-descriptive-statistics.html](03-descriptive-statistics.html)
- Презентация [03.2-types-of-means.html](03.2-types-of-means.html)  (самостоятельно)

## 4. Работа с данными, описательная статистика в R

- Код [04-data-in-r.R](04-data-in-r.R)
- Данные:
    - [passive-smoke.txt](data/passive-smoke.txt)
    - [cholesterol-and-smoking.txt](data/cholesterol-and-smoking.txt)

## 5-6. Визуализация данных. Графики в пакете ggplot2

- Презентация [05-data-visualisation.html](05-data-visualisation.html)
- Код [06-ggplot2.R](06-ggplot2.R)
- Данные:
    - [penguins.xlsx](data/penguins.xlsx)
- Задание:
    - [06-ggplot2-tasks.html](06-ggplot2-tasks.html)
    
- Данные для домашнего задания: [IHME-GBD_2019_injuries_and_cancer.csv](data/IHME-GBD_2019_injuries_and_cancer.csv)


## 7-8. Вероятности и распределения

- Презентация [07-probabilities.html](07-probabilities.html)
- Презентация [07.2-monty-hall-problem.html](07.2-monty-hall-problem.html) (самостоятельно для развлечения)
- Код [08-probabilities-in-r.R](08-probabilities-in-r.R)

## 9-10. Доверительные интервалы. Тестирование гипотез.

- Презентация [09-confidence-intervals-and-hypothesis-testing.html](09-confidence-intervals-and-hypothesis-testing.html)
- Код [10-confidence-intervals-and-hypothesis-testing-in-r.R](10-confidence-intervals-and-hypothesis-testing-in-r.R)
- Данные [memory.csv](data/memory.csv)

## 11-12. Cравнение двух групп

- Презентация [11-comparing-two-groups.html](11-comparing-two-groups.html)
- Код [12-comparing-two-groups-in-r.R](12-comparing-two-groups-in-r.R)


## 13-14. Пропорции и частоты

- Презентация [13-proportions-and-frequencies.html](13-proportions-and-frequencies.html)
- Код [14-proportions-and-frequencies-in-r.R](14-proportions-and-frequencies-in-r.R)

## 15-16. Случайность в пространстве или времени

- Презентация [15-randomness-in-space-and-time.html](15-randomness-in-space-and-time.html)
- Код [16-randomness-in-space-and-time-in-r.R](16-randomness-in-space-and-time-in-r.R)
- Данные:
  - [DayOfBirth2016.csv](data/DayOfBirth2016.csv)
  - [RaupSepkoski1982MassExtinctions.csv](data/RaupSepkoski1982MassExtinctions.csv)
  - [Klem_etal.2004_BirdWindowCrash.csv](data/Klem_etal.2004_BirdWindowCrash.csv)
  - [Cavalry.csv](data/Cavalry.csv)
  - [Waters_etal.1997_Truffles.csv](data/Waters_etal.1997_Truffles.csv)

## 17-18. Связь между категориальными переменными

- Презентация [17-assotiation-between-categorical-data.html](17-assotiation-between-categorical-data.html)
- Код [18-assotiation-between-categorical-data-in-r.R](18-assotiation-between-categorical-data-in-r.R)
- Данные:
  - [aspirin_cancer_Cook_etal_2005.csv](data/aspirin_cancer_Cook_etal_2005.csv)
  - [toxoplasma_driving_Yereli_etal_2006.csv](data/toxoplasma_driving_Yereli_etal_2006.csv)
  - [trematodes_behaviour_Lafferty_Morris_1996.csv](data/trematodes_behaviour_Lafferty_Morris_1996.csv)
  - [vampires_Turner_1975.csv](data/vampires_Turner_1975.csv)
  - [Titanic_sex_and_survival.csv](data/Titanic_sex_and_survival.csv)


## 19-20. Дисперсионный анализ

- Презентация [19-anova.html](19-anova.html)
- Код [20-anova-in-R.R](20-anova-in-R.R)
- Данные:
  - [melatonin_Wright_Czeisler_2002.csv](data/melatonin_Wright_Czeisler_2002.csv)
  - [walking_stick_femurs_Nosil_Crespi_2006.csv](data/walking_stick_femurs_Nosil_Crespi_2006.csv)
  - [zostera_Reusch_etal_2005.csv](data/zostera_Reusch_etal_2005.csv)
  - [dung_beetles_Kotiaho_etal_2001.csv](data/dung_beetles_Kotiaho_etal_2001.csv)

## 21-22. Корреляция и регрессия

- Презентация [21-correlation-and-regression.html](21-correlation-and-regression.html)
- Код [22-correlation-and-regression-in-r.R](22-correlation-and-regression-in-r.R)
- Данные:
  - [lions_Whitman_etal_2004.csv](data/lions_Whitman_etal_2004.csv)
  - [wolves_inbreeding_Liberg_etal_2005.csv](data/wolves_inbreeding_Liberg_etal_2005.csv)
  - [iris_pollen_Pauw_etal_2009.csv](data/iris_pollen_Pauw_etal_2009.csv)
  - [beetle_horns_Emlen_2001.csv](data/beetle_horns_Emlen_2001.csv)

## 23-24. Ограничения статистических методов. Непараметрические методы

<!-- - Презентация [23-assumptions-and-nonparametrics.html](23-assumptions-and-nonparametrics.html) -->
- Код [24-assumptions-and-nonparametrics-in-r.R](24-assumptions-and-nonparametrics-in-r.R)
- Данные:
  - [marine_reserve_Halpern_2003.csv](data/marine_reserve_Halpern_2003.csv)
  - [sexual_conflict_Arnqvist_etal_2000.csv](data/sexual_conflict_Arnqvist_etal_2000.csv)
  - [mating_time_Chadwick_etal_1999.csv](data/mating_time_Chadwick_etal_1999.csv)
  - с прошлого занятия [lions_Whitman_etal_2004.csv](data/lions_Whitman_etal_2004.csv)

